FROM ubuntu:16.04
MAINTAINER Luiz Coura <luizcoura@gmail.com>

# Update Ubuntu
RUN apt-get update && apt-get upgrade -y

# install openssh-server vim openjdk8-jdk
RUN apt-get install -y openssh-server vim
RUN apt-get install -y openjdk-8-jdk