#!/bin/sh
while true; do
    lat=$RANDOM
    let "lat%=90"
    lon=$RANDOM
    let "lon%=180"
    alt=$RANDOM
    let "alt%=2000"
    val=$RANDOM
    echo "{\"d\":{\"tipo\":7,\"lat\":$lat,\"lon\":$lon,\"alt\":$alt,\"val\":$val},\"ts\":`date +'%s'`}"
    sleep 1
done | mosquitto_pub -i "br.ita.bditac.inbound.pub" -q 1 -d -l -t "br.ita.bditac/test"
